### ISSUE TITLE
[1.18.2 - 1.0.0] Login Timeout Unchanged

### ISSUE THREAD

**Issue by jkwphysics** [Dremoline/LongerLoginTimes#1]
**Version info**
Minecraft 1.18.2
Forge 40.0.32
LongerLoginTimes 1.0.0

**Describe the bug**
Using this mod doesn't seem to change the timeout period. In going through the server debug.log, the times span for the handshake is still limited to around 30 seconds before the "timed out" message appears and player is unable to join.

`[Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@a827f4a[id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx,name=name,properties={textures=[com.mojang.authlib.properties.Property@62709a28]},legacy=false] (/555.555.555.55:50100) lost connection: Timed out`

**To Reproduce**
Difficult to reproduce - a slower PC with a modpack of around 200 mods will likely have login issues on MC 1.18.2.

**Comment by SuperMartijn642** [comment]
When a client connects to a server, there's 30 seconds for the client to load everything before getting disconnected. Longer Login Times changes those 30 seconds to a user defined duration.
After the client has loaded everything and joins the world, the client needs to send a keep alive message to the server at least every 15 seconds.

In your case the client got ticked because the duration between keep alive packets was longer than 15 seconds. This can be caused by a bad network connection or simply the computer being too slow to keep up with the server.
Anyways, this is not something Longer Login Times aims to solve.
